# Generated by Django 2.2.4 on 2019-08-05 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='event_invitees',
            field=models.ManyToManyField(blank=True, related_name='invitees', to=settings.AUTH_USER_MODEL),
        ),
    ]
