# Generated by Django 2.2.4 on 2019-08-05 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SchedAPI', '0002_auto_20190805_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='event_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
