# Generated by Django 2.2.4 on 2019-08-05 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchedAPI', '0003_auto_20190805_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to=settings.AUTH_USER_MODEL),
        ),
    ]
